### ISSUE TITLE
Problems caused by protoc version

### ISSUE THREAD

**Issue by AIGeorgeLi** [NeuraSearch/NeurIPS-2022-Submission-3358#2]

**Comment by AIGeorgeLi** [comment]
Run "./start_train.sh" under the pycharm terminal/bash_script$, and get the following error, prompting an error "" Follow the prompts to update protoc to the latest version ( protoc ) and downgrade to 3.20.*, both methods have been tried; but the problem The problem also exists after execution, how to solve it, thank you.
 
Error :
       message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:

Downgrade the protobuf package to 3.20.x or lower.
Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by KnightZhang625** [comment]
Hi, there. I ran the bash on both my local machine and server, and it works as usual. Regarding to your question, I believe it's your local environment problems. Since it looks like the problem has nothing relevant to the packages or code. Probably you could try to assign the args value in the python file, instead of from terminal (i.e, through bash).

Thanks!

**Comment by AIGeorgeLi** [comment]
Yeah, thanks for your answer. The problem has been solved: I tried to download the entire code zip file locally and run it, everything works fine, thanks for your support.

**Comment by AIGeorgeLi** [comment]
> Hi, there. I ran the bash on both my local machine and server, and it works as usual. Regarding to your question, I believe it's your local environment problems. Since it looks like the problem has nothing relevant to the packages or code. Probably you could try to assign the args value in the python file, instead of from terminal (i.e, through bash).
> 
> Thanks!

Yeah, thanks for your answer. The problem has been solved: I tried to download the entire code zip file locally and run it, everything works fine, thanks for your support.

**Comment by AIGeorgeLi** [comment]
> Hi, there. I ran the bash on both my local machine and server, and it works as usual. Regarding to your question, I believe it's your local environment problems. Since it looks like the problem has nothing relevant to the packages or code. Probably you could try to assign the args value in the python file, instead of from terminal (i.e, through bash).
> 
> Thanks!

thanks for your answer. I tried to download the entire code zip file to the local instead of the previous direct clone code, and everything worked fine, thank you for your support.

**Comment by KnightZhang625** [comment]
> > Hi, there. I ran the bash on both my local machine and server, and it works as usual. Regarding to your question, I believe it's your local environment problems. Since it looks like the problem has nothing relevant to the packages or code. Probably you could try to assign the args value in the python file, instead of from terminal (i.e, through bash).
> > Thanks!
> 
> thanks for your answer. I tried to download the entire code zip file to the local instead of the previous direct clone code, and everything worked fine, thank you for your support.

Great, glad you solve the problem. Feel free to ask me if you have further problems.
